apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: delivery-manager
  labels:
    app: delivery-manager

spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-manager
  template:
    metadata:
      labels:
        app: delivery-manager
    spec:
      containers:
      - name: delivery-manager
        image: dhf0820/delivery-manager:latest
        env:
        - name: SERVICE
          value: 'delivery-manager'
        - name: CUSTOMER
          value: 'cutter'
        - name: MONGO_ENV
          value: k8s_local
        - name: IDS_ATLAS_DEV_URI
          valueFrom:
            secretKeyRef:
              name: dev-mongo-uri
              key: IDS_ATLAS_DEV_URI
      imagePullSecrets:
      - name: regcred
      