version: '3.2'
services:
  server:
    build: .
    #command: bundle exec rackup -p 3000
    environment:
      - CUSTOMER=ids
      - SERVICE=image

#    env_file:
#      - '.env'
#    ports:
#      - "4567:4567"

