require 'rubygems'
require 'bundler'
Bundler::GemHelper.install_tasks
##gem 'hoe' , '>= 3.14.2' #, '>= 2.1.0'
##require 'hoe'
#require 'fileutils'
#require './lib/report-reader'


#Dir['tasks/**/*.rake'].each { |t| load t }

# TODO - want other tests/tasks run by default? Add them to the list
# remove_task :default
# task :default => [:spec, :features]
