apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rad-parser
  labels:
    app: rad-parser

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rad-parser
  template:
    metadata:
      labels:
        app: rad-parser
    spec:
      containers:
      - name: rad-parser
        image: dhf0820/reader:0.13.12
        env:
        - name: SERVICE
          value: 'rad'
        - name: CUSTOMER
          value: 'ids'
      imagePullSecrets:
      - name: regcred

# kubectl create secret docker-registry regcred --docker-server='https://index.docker.io/v1/' --docker-username='dhf0820' --docker-password='dEnyedi57!o' --docker-email='dhfrench@vertisoft.com'
